=== srivas-saksham/Web-Tech/Lab Assignments/Lab Questions 1 to 20/Question 23 (27-10-24)/index.dtd
<!ELEMENT teachers (teacher+)>
<!ELEMENT teacher (name, subject, experience)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT subject (#PCDATA)>
<!ELEMENT experience (#PCDATA)>
<!ATTLIST teacher id CDATA #REQUIRED>

=== srivas-saksham/Web-Tech/Lab Assignments/Lab Questions 1 to 20/Question 23 (27-10-24)/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style.css"?>

<!DOCTYPE teachers SYSTEM "index.dtd">

<teachers>
    <teacher id="1">
        <name>Thehar Patel</name>
        <subject>Mathematics</subject>
        <experience>10</experience>
    </teacher>
    <teacher id="2">
        <name>Ranujan Kappa</name>
        <subject>Physics</subject>
        <experience>5</experience>
    </teacher>
    <teacher id="3">
        <name>Selesky Damodar</name>
        <subject>Chemistry</subject>
        <experience>8</experience>
    </teacher>
</teachers>
